sudo: false

install: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

script:
  - export SONARQUBE_SKIPPED=
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.login=$SONAR_TOKEN

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: 'target/sonar-rci-plugin-*.jar'
  skip_cleanup: true
  on:
    tags: true